package com.csxh.model;
// Generated 2015-11-4 14:55:03 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private int id;
	private Integer orderId;
	private Integer customerId;
	private Integer payMethodId;
	private Serializable deliverName;
	private Serializable deliverCity;
	private Serializable deliverAddres;
	private Serializable deliverZip;
	private Serializable deliverPhone;
	private Integer shippingId;
	private Date orderDate;
	private boolean finished;
	private Date finishedTime;
	private Serializable adminName;
	private Integer adminId;

	public Order() {
	}

	public Order(int id, boolean finished) {
		this.id = id;
		this.finished = finished;
	}

	public Order(int id, Integer orderId, Integer customerId, Integer payMethodId, Serializable deliverName,
			Serializable deliverCity, Serializable deliverAddres, Serializable deliverZip, Serializable deliverPhone,
			Integer shippingId, Date orderDate, boolean finished, Date finishedTime, Serializable adminName,
			Integer adminId) {
		this.id = id;
		this.orderId = orderId;
		this.customerId = customerId;
		this.payMethodId = payMethodId;
		this.deliverName = deliverName;
		this.deliverCity = deliverCity;
		this.deliverAddres = deliverAddres;
		this.deliverZip = deliverZip;
		this.deliverPhone = deliverPhone;
		this.shippingId = shippingId;
		this.orderDate = orderDate;
		this.finished = finished;
		this.finishedTime = finishedTime;
		this.adminName = adminName;
		this.adminId = adminId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Integer getPayMethodId() {
		return this.payMethodId;
	}

	public void setPayMethodId(Integer payMethodId) {
		this.payMethodId = payMethodId;
	}

	public Serializable getDeliverName() {
		return this.deliverName;
	}

	public void setDeliverName(Serializable deliverName) {
		this.deliverName = deliverName;
	}

	public Serializable getDeliverCity() {
		return this.deliverCity;
	}

	public void setDeliverCity(Serializable deliverCity) {
		this.deliverCity = deliverCity;
	}

	public Serializable getDeliverAddres() {
		return this.deliverAddres;
	}

	public void setDeliverAddres(Serializable deliverAddres) {
		this.deliverAddres = deliverAddres;
	}

	public Serializable getDeliverZip() {
		return this.deliverZip;
	}

	public void setDeliverZip(Serializable deliverZip) {
		this.deliverZip = deliverZip;
	}

	public Serializable getDeliverPhone() {
		return this.deliverPhone;
	}

	public void setDeliverPhone(Serializable deliverPhone) {
		this.deliverPhone = deliverPhone;
	}

	public Integer getShippingId() {
		return this.shippingId;
	}

	public void setShippingId(Integer shippingId) {
		this.shippingId = shippingId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public boolean isFinished() {
		return this.finished;
	}

	public void setFinished(boolean finished) {
		this.finished = finished;
	}

	public Date getFinishedTime() {
		return this.finishedTime;
	}

	public void setFinishedTime(Date finishedTime) {
		this.finishedTime = finishedTime;
	}

	public Serializable getAdminName() {
		return this.adminName;
	}

	public void setAdminName(Serializable adminName) {
		this.adminName = adminName;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

}
