package com.csxh.model;
// Generated 2015-11-4 14:11:07 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

/**
 * PaymethodId generated by hbm2java
 */
public class Paymethod implements java.io.Serializable {

	private int id;
	private String name;

	public Paymethod() {
	}

	public Paymethod(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Paymethod other = (Paymethod) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Paymethod [id=" + id + ", name=" + name + "]";
	}

	
}
