package com.csxh.model;
// Generated 2015-11-4 14:11:07 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ShippingId generated by hbm2java
 */
public class Shipping implements java.io.Serializable {

	private int id;
	private String name;
	private double fee;

	public Shipping() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getFee() {
		return fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee.doubleValue();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Shipping other = (Shipping) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Shipping [id=" + id + ", name=" + name + ", fee=" + fee + "]";
	}

	
}
